# Generated by Django 5.2.16 on 2026-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Токен доступа'),
        ),
    ]
