name: Django CI/CD Pipeline

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка исходного кода (Checkout)
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Проверка стиля кода линтером (Flake8)
      run: |
        flake8 . --count --exclude=.git,__pycache__,env,venv,migrations --max-line-length=120 --statistics

    - name: Проверка миграций базы данных Django
      run: |
        python manage.py makemigrations --check --dry-run
        python manage.py migrate
